<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="firefox.Protractor Demo App" timestamp="2016-02-21T20:50:27" hostname="localhost" time="4.63" errors="0" tests="1" skipped="0" disabled="0" failures="1">
  <testcase classname="firefox.Protractor Demo App" name="should add one and two|firefox|44.0" time="4.629">
   <failure type="toEqual" message="Expected &apos;3&apos; to equal &apos;5&apos;."><![CDATA[Error: Failed expectation
    at Object.<anonymous> (C:\workspace\BasicProtractorGrunt\tests\e2e\demo-sites\specs\supercalculator-suposed-to-fail-spec.js:13:51)
    at C:\workspace\BasicProtractorGrunt\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\jasminewd2\index.js:96:23
    at [object Object].promise.Promise.goog.defineClass.constructor (C:/workspace/BasicProtractorGrunt/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1056:7)
    at new wrappedCtr (C:\workspace\BasicProtractorGrunt\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:2468:26)
    at controlFlowExecute (C:\workspace\BasicProtractorGrunt\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\jasminewd2\index.js:82:18)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (C:/workspace/BasicProtractorGrunt/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (C:/workspace/BasicProtractorGrunt/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (C:\workspace\BasicProtractorGrunt\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
    at process._tickCallback (node.js:368:9)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>